stages:
  - build
  - import
  - publish

variables:
  PYVERS: cp37|cp38|cp39|cp310|cp311


.artifacts:
  artifacts:
    paths:
    - dist/*.tar.gz
    - dist/*.whl


.always:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour


.devel:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour
  except:
  - tags


.release:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour
  only:
  - tags


.keep:
  extends: .artifacts
  artifacts:
    expire_in: 1000 years
  only:
  - tags


.manylinux1_i686: &manylinux1_i686
  image: quay.io/pypa/manylinux1_i686
  variables:
    PYVERS: cp37|cp38|cp39



.manylinux1_x86_64: &manylinux1_x86_64
  image: quay.io/pypa/manylinux1_x86_64
  variables:
    PYVERS: cp37|cp38|cp39


.manylinux2010_i686: &manylinux2010_i686
  image: quay.io/pypa/manylinux2010_i686
  variables:
    PYVERS: cp37|cp38|cp39


.manylinux2010_x86_64: &manylinux2010_x86_64
  image: quay.io/pypa/manylinux2010_x86_64
  variables:
    PYVERS: cp37|cp38|cp39


.manylinux2014_i686: &manylinux2014_i686
  image: quay.io/pypa/manylinux2014_i686
  variables:
    PYVERS: cp37|cp38|cp39


.manylinux2014_x86_64: &manylinux2014_x86_64
  image: quay.io/pypa/manylinux2014_x86_64


.manylinux_2_24_i686: &manylinux_2_24_i686
  image: quay.io/pypa/manylinux_2_24_i686
  variables:
    PYVERS: cp37|cp38|cp39


.manylinux_2_24_x86_64: &manylinux_2_24_x86_64
  image: quay.io/pypa/manylinux_2_24_x86_64


.manylinux_2_24_aarch64: &manylinux_2_24_aarch64
  image: quay.io/pypa/manylinux_2_24_aarch64
  tags:
    - arm


.build: &build
  stage: build
  script:
  - ./build_wheels.sh

.source: &source
  stage: build
  script:
  - ./build_sdist.sh


.publish:
  extends: .keep
  stage: publish
  script:
  - ./publish_wheels.sh


devel-source:
  <<: *manylinux_2_24_x86_64
  <<: *source
  extends: .devel


devel-manylinux1_i686:
  <<: *manylinux1_i686
  <<: *build
  extends: .devel


devel-manylinux1_x86_64:
  <<: *manylinux1_x86_64
  <<: *build
  extends: .devel


devel-manylinux2010_x86_64:
  <<: *manylinux2010_x86_64
  <<: *build
  extends: .devel


devel-manylinux2010_i686:
  <<: *manylinux2010_i686
  <<: *build
  extends: .devel


devel-manylinux2014_i686:
  <<: *manylinux2014_i686
  <<: *build
  extends: .devel


devel-manylinux2014_x86_64:
  <<: *manylinux2014_x86_64
  <<: *build
  extends: .devel


devel-manylinux_2_24_aarch64:
  <<: *manylinux_2_24_aarch64
  <<: *build
  extends: .devel


devel-manylinux_2_24_i686:
  <<: *manylinux_2_24_i686
  <<: *build
  extends: .devel


devel-manylinux_2_24_x86_64:
  <<: *manylinux_2_24_x86_64
  <<: *build
  extends: .devel


release-source:
  <<: *manylinux_2_24_x86_64
  <<: *source
  extends: .release


release-manylinux1_i686:
  <<: *manylinux1_i686
  <<: *build
  extends: .release


release-manylinux1_x86_64:
  <<: *manylinux1_x86_64
  <<: *build
  extends: .release


release-manylinux2010_i686:
  <<: *manylinux2010_i686
  <<: *build
  extends: .release


release-manylinux2010_x86_64:
  <<: *manylinux2010_x86_64
  <<: *build
  extends: .release


release-manylinux2014_i686:
  <<: *manylinux2014_i686
  <<: *build
  extends: .release


release-manylinux2014_x86_64:
  <<: *manylinux2014_x86_64
  <<: *build
  extends: .release


release-manylinux_2_24_aarch64:
  <<: *manylinux_2_24_aarch64
  <<: *build
  extends: .release


release-manylinux_2_24_i686:
  <<: *manylinux_2_24_i686
  <<: *build
  extends: .release


release-manylinux_2_24_x86_64:
  <<: *manylinux_2_24_x86_64
  <<: *build
  extends: .release


import-appveyor:
  <<: *manylinux_2_24_x86_64
  stage: import
  extends: .always
  script:
  - /opt/python/cp39-cp39/bin/python import_appveyor.py
  - ./check_artifacts.sh


publish:
  <<: *manylinux_2_24_x86_64
  extends: .publish
  needs: [
    "release-source",
    "release-manylinux1_i686",
    "release-manylinux1_x86_64",
    "release-manylinux2010_i686",
    "release-manylinux2010_x86_64",
    "release-manylinux2014_i686",
    "release-manylinux2014_x86_64",
    "release-manylinux_2_24_aarch64",
    "release-manylinux_2_24_i686",
    "release-manylinux_2_24_x86_64",
    "import-appveyor"
  ]
