stages:
  - build
  - publish


.build:
  stage: build
  script:
  - ./build-wheels.sh
  artifacts:
    paths:
    - dist/*.tar.gz
    - dist/*.whl


.devel:
  extends: .build
  artifacts:
    expire_in: 8 hours
  except:
  - tags


.release:
  extends: .build
  artifacts:
    expire_in: 1000 years
  only:
  - tags


.publish:
  stage: publish
  script:
  - ./publish-wheels.sh
  only:
  - tags


.x86_64: &x86_64
  image: quay.io/pypa/manylinux1_x86_64


.i686: &i686
  image: quay.io/pypa/manylinux1_i686


devel:
  <<: *x86_64
  extends: .devel


devel-i686:
  <<: *i686
  extends: .devel


release:
  <<: *x86_64
  extends: .release


release-i686:
  <<: *i686
  extends: .release


publish:
  <<: *x86_64
  extends: .publish
