stages:
  - build
  - import
  - publish


.artifacts:
  artifacts:
    paths:
    - dist/*.tar.gz
    - dist/*.whl


.always:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour


.devel:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour
  except:
  - tags


.release:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour
  only:
  - tags


.keep:
  extends: .artifacts
  artifacts:
    expire_in: 1000 years
  only:
  - tags


.x86_64-manylinux1: &x86_64-manylinux1
  image: quay.io/pypa/manylinux1_x86_64


.x86_64-manylinux2010: &x86_64-manylinux2010
  image: quay.io/pypa/manylinux2010_x86_64


.i686-manylinux1: &i686-manylinux1
  image: quay.io/pypa/manylinux1_i686


.i686-manylinux2010: &i686-manylinux2010
  image: quay.io/pypa/manylinux2010_i686


.aarch64-manylinux2014: &aarch64-manylinux2014
  image: quay.io/pypa/manylinux2014_aarch64


.build: &build
  stage: build
  script:
  - ./install_cmake.sh
  - ./build_wheels.sh


.publish:
  extends: .keep
  stage: publish
  script:
  - ./publish_wheels.sh


devel-x86_64-manylinux1:
  <<: *x86_64-manylinux1
  <<: *build
  extends: .devel


devel-x86_64-manylinux2010:
  <<: *x86_64-manylinux2010
  <<: *build
  extends: .devel


devel-i686-manylinux1:
  <<: *i686-manylinux1
  <<: *build
  extends: .devel


devel-i686-manylinux2010:
  <<: *i686-manylinux2010
  <<: *build
  extends: .devel


devel-aarch64-manylinux2014:
  image: docker:latest
  script:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker run --privileged -v `pwd`:`pwd` -w `pwd` quay.io/pypa/manylinux2014_aarch64 /bin/bash -c "./install_cmake.sh && ./build_wheels.sh"
  extends: .devel


release-x86_64-manylinux1:
  <<: *x86_64-manylinux1
  <<: *build
  extends: .release


release-x86_64-manylinux2010:
  <<: *x86_64-manylinux2010
  <<: *build
  extends: .release


release-i686-manylinux1:
  <<: *i686-manylinux1
  <<: *build
  extends: .release


release-i686-manylinux2010:
  <<: *i686-manylinux2010
  <<: *build
  extends: .release


release-aarch64-manylinux2014:
  image: docker:latest
  script:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker run --privileged -v `pwd`:`pwd` -w `pwd` quay.io/pypa/manylinux2014_aarch64 /bin/bash -c "./install_cmake.sh && ./build_wheels.sh"
  extends: .release


import-appveyor:
  <<: *x86_64-manylinux2010
  stage: import
  extends: .always
  script:
  - /opt/python/cp38-cp38/bin/python import_appveyor.py
  - /opt/python/cp38-cp38/bin/pip install -r build_requirements.txt
  - /opt/python/cp38-cp38/bin/python setup.py sdist --dist-dir=dist
  - ./check_artifacts.sh


publish:
  <<: *x86_64-manylinux2010
  extends: .publish
  needs: [
    "release-x86_64-manylinux1",
    "release-x86_64-manylinux2010",
    "release-i686-manylinux1",
    "release-i686-manylinux2010",
    "import-appveyor"
  ]
