stages:
  - dependencies
  - build
  - external
  - import
  - publish


.artifacts:
  artifacts:
    paths:
    - lib/*
    - dist/*.tar.gz
    - dist/*.whl


.always:
  extends: .artifacts
  artifacts:
    expire_in: 8 hours


.devel:
  extends: .artifacts
  artifacts:
    expire_in: 8 hours
  except:
  - tags


.release:
  extends: .artifacts
  artifacts:
    expire_in: 1000 years
  only:
  - tags


.publish:
  stage: publish
  script:
  - ./publish-wheels.sh
  only:
  - tags


.x86_64: &x86_64
  image: quay.io/pypa/manylinux2010_x86_64


.i686: &i686
  image: quay.io/pypa/manylinux2010_i686


.build: &build
  stage: build
  script:
  - ./build-wheels.sh


.dependencies: &dependencies
  stage: dependencies
  script:
  - ./build-turbojpeg.sh


dependencies:
  <<: *x86_64
  <<: *dependencies
  extends: .always


dependencies-i686:
  <<: *i686
  <<: *dependencies
  extends: .always


devel:
  <<: *x86_64
  <<: *build
  extends: .devel
  needs: ["dependencies"]


devel-i686:
  <<: *i686
  <<: *build
  extends: .devel
  needs: ["dependencies-i686"]


release:
  <<: *x86_64
  <<: *build
  extends: .release
  needs: ["dependencies"]


release-i686:
  <<: *i686
  <<: *build
  extends: .release
  needs: ["dependencies-i686"]


import-appveyor:
  <<: *x86_64
  stage: import
  extends: .always
  script:
    - /opt/python/cp38/bin/python import_appveyor.py


publish:
  <<: *x86_64
  extends: .publish
  needs: ["release", "release-i686", "import-appveyor"]
