stages:
  - build
  - import
  - publish


.artifacts:
  artifacts:
    paths:
    - dist/*.tar.gz
    - dist/*.whl


.always:
  extends: .artifacts
  artifacts:
    expire_in: 8 hours


.devel:
  extends: .artifacts
  artifacts:
    expire_in: 8 hours
  except:
  - tags


.release:
  extends: .artifacts
  artifacts:
    expire_in: 1000 years
  only:
  - tags


.publish:
  stage: publish
  script:
  - ./publish-wheels.sh
  only:
  - tags


.x86_64: &x86_64
  image: quay.io/pypa/manylinux2010_x86_64


.i686: &i686
  image: quay.io/pypa/manylinux2010_i686


.build: &build
  stage: build
  script:
  - yum update -y
  - yum install -y cmake
  - ./build-wheels.sh


devel:
  <<: *x86_64
  <<: *build
  extends: .devel


devel-i686:
  <<: *i686
  <<: *build
  extends: .devel


release:
  <<: *x86_64
  <<: *build
  extends: .release


release-i686:
  <<: *i686
  <<: *build
  extends: .release


import-appveyor:
  <<: *x86_64
  stage: import
  extends: .always
  script:
    - /opt/python/cp38-cp38/bin/python import_appveyor.py
    - /opt/python/cp38-cp38/bin/pip install -r build-requirements.txt
    - /opt/python/cp38-cp38/bin/python setup.py sdist --dist-dir=dist


publish:
  <<: *x86_64
  extends: .publish
  needs: ["release", "release-i686", "import-appveyor"]
