branches:
  only:
    - master

image:
  - macOS
  - Visual Studio 2019

environment:
  VCVARSALL: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat'
  MACOSX_DEPLOYMENT_TARGET: "10.9"
  matrix:
    # See appveyor docs for available Python versions:
    # https://www.appveyor.com/docs/windows-images-software/#python
    - platform: x86
      INTERPRETERS: "C:\\Python35;C:\\Python36;C:\\Python37;C:\\Python38"
    - platform: x64
      INTERPRETERS: "C:\\Python35-x64;C:\\Python36-x64;C:\\Python37-x64;C:\\Python38-x64"

for:
  -
    matrix:
      exclude:
        - image: macOS
          platform: x86
  -
    matrix:
      only:
        - image: Visual Studio 2019
    build_script:
      - ps: .\build_wheels.ps1
    artifacts:
      - path: dist\*.whl
  -
    matrix:
      only:
        - image: macOS
    environment:
      INTERPRETERS: "3.5-dev 3.6-dev 3.7-dev 3.8-dev"
    build_script:
      - ps: ./build_wheels_macos.sh
    artifacts:
      - path: dist/*.whl
